// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/token": {
            "get": {
                "description": "APS サービス用の認証トークンを取得",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "認証"
                ],
                "summary": "トークン取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TokenResponse"
                        }
                    }
                }
            }
        },
        "/buckets": {
            "get": {
                "description": "バケット一覧を取得",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "バケット"
                ],
                "summary": "バケット一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Bucket"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "新規バケットを作成",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "バケット"
                ],
                "summary": "バケット作成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BucketResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Bucket": {
            "type": "object",
            "properties": {
                "bucketKey": {
                    "type": "string"
                },
                "bucketOwner": {
                    "type": "string"
                },
                "createdDate": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Permission"
                    }
                },
                "policyKey": {
                    "type": "string"
                }
            }
        },
        "domain.Permission": {
            "type": "object",
            "properties": {
                "access": {
                    "type": "string"
                },
                "authId": {
                    "type": "string"
                }
            }
        },
        "handler.BucketResponse": {
            "type": "object",
            "properties": {
                "created_date": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "policy_key": {
                    "type": "string"
                }
            }
        },
        "handler.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_in": {
                    "type": "integer"
                },
                "token_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Nextgo APS Viewer API",
	Description:      "API for APS Viewer application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
