definitions:
  domain.APSBucket:
    properties:
      bucketKey:
        type: string
      bucketOwner:
        type: string
      createdDate:
        type: integer
      permissions:
        items:
          $ref: '#/definitions/domain.Permission'
        type: array
      policyKey:
        type: string
    type: object
  domain.APSToken:
    description: APSトークンレスポンス
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      expires_in:
        example: 3599
        type: integer
      refresh_token:
        example: ""
        type: string
      token_type:
        example: Bearer
        type: string
    type: object
  domain.Permission:
    properties:
      access:
        type: string
      authId:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/buckets:
    post:
      consumes:
      - application/json
      description: 新しいAPSバケットを作成します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APSBucket'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: APSバケット作成
      tags:
      - APS Bucket
  /api/v1/token:
    post:
      consumes:
      - application/json
      description: 2-legged認証でAPSアクセストークンを取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APSToken'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: APSトークン取得
      tags:
      - APS Token
swagger: "2.0"
