basePath: /api/v1
definitions:
  handler.BucketResponse:
    properties:
      created_date:
        type: string
      name:
        type: string
      policy_key:
        type: string
    type: object
  handler.TokenResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      token_type:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for APS Viewer application
  title: Nextgo APS Viewer API
  version: "1.0"
paths:
  /auth/token:
    get:
      consumes:
      - application/json
      description: APS サービス用の認証トークンを取得
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.TokenResponse'
      summary: トークン取得
      tags:
      - 認証
  /buckets:
    post:
      consumes:
      - application/json
      description: 新規バケットを作成
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.BucketResponse'
      summary: バケット作成
      tags:
      - バケット
swagger: "2.0"
