definitions:
  aps_bucket.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  aps_object.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  domain.APSBucket:
    properties:
      bucketKey:
        type: string
      createdDate:
        type: integer
      policyKey:
        type: string
    type: object
  domain.APSBucketDetail:
    properties:
      bucketKey:
        type: string
      bucketOwner:
        type: string
      createdDate:
        type: integer
      permissions:
        items:
          $ref: '#/definitions/domain.Permission'
        type: array
      policyKey:
        type: string
    type: object
  domain.APSObject:
    properties:
      uploadExpiration:
        type: string
      uploadKey:
        type: string
      urlExpiration:
        type: string
      urls:
        items:
          type: string
        type: array
    type: object
  domain.APSToken:
    description: APSトークンレスポンス
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        type: string
      expires_in:
        example: 3599
        type: integer
      refresh_token:
        example: ""
        type: string
      token_type:
        example: Bearer
        type: string
    type: object
  domain.Permission:
    properties:
      access:
        type: string
      authId:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: APS Token Management API
  title: APS Viewer API
  version: "1.0"
paths:
  /api/v1/aps/buckets:
    get:
      consumes:
      - application/json
      description: Get list of all buckets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.APSBucket'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
      security:
      - Bearer: []
      summary: Get buckets list
      tags:
      - APS Bucket
    post:
      consumes:
      - application/json
      description: 新しいAPSバケットを作成します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APSBucket'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
      summary: APSバケット作成
      tags:
      - APS Bucket
  /api/v1/aps/buckets/{bucketKey}:
    delete:
      consumes:
      - application/json
      description: 指定されたバケットを削除します
      parameters:
      - description: バケットキー
        in: path
        name: bucketKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
      summary: APSバケット削除
      tags:
      - APS Bucket
  /api/v1/aps/buckets/{bucketKey}/details:
    get:
      consumes:
      - application/json
      description: 指定されたバケットの詳細情報を取得します
      parameters:
      - description: バケットキー
        in: path
        name: bucketKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APSBucketDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/aps_bucket.ErrorResponse'
      summary: APSバケット詳細取得
      tags:
      - APS Bucket
  /api/v1/aps/buckets/{bucketKey}/objects/signeds3upload:
    post:
      consumes:
      - multipart/form-data
      description: オブジェクトをS3へ保存するためのS3署名付きURLを取得します
      parameters:
      - description: バケットキー
        in: path
        name: bucketKey
        required: true
        type: string
      - description: アップロードするファイル
        in: formData
        name: file
        required: true
        type: file
      - default: 1
        description: パート数
        in: query
        name: parts
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APSObject'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/aps_object.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/aps_object.ErrorResponse'
      summary: S3署名付きURLの取得
      tags:
      - APS Object
  /api/v1/aps/buckets/{bucketKey}/objects/upload:
    post:
      consumes:
      - multipart/form-data
      description: S3署名付きURLを取得してオブジェクトをアップロードするシーケンスを実行します
      parameters:
      - description: バケットキー
        in: path
        name: bucketKey
        required: true
        type: string
      - description: アップロードするファイル
        in: formData
        name: file
        required: true
        type: file
      - default: 1
        description: パート数
        in: query
        name: parts
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/aps_object.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/aps_object.ErrorResponse'
      summary: APSオブジェクトのアップロードシーケンス
      tags:
      - APS Object
  /api/v1/aps/objects/signeds3upload:
    put:
      consumes:
      - application/octet-stream
      description: S3署名付きURLを使用してオブジェクトをS3へアップロードします
      parameters:
      - description: 署名付きURL
        in: query
        name: signedURL
        required: true
        type: string
      - description: アップロードするファイルのバイナリデータ
        in: body
        name: file
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/aps_object.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/aps_object.ErrorResponse'
      summary: S3署名付きURLを使用したオブジェクトのアップロード
      tags:
      - APS Object
  /api/v1/aps/token:
    post:
      consumes:
      - application/json
      description: 2-legged認証でAPSアクセストークンを取得します
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.APSToken'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: APSトークン取得
      tags:
      - APS Token
swagger: "2.0"
